# -*- coding: utf-8 -*-
"""Untitled12.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cJO5SaTyQ4DigoHoNzwqx9oCC7wFU4Je
"""

!pip install tuya-iot-py-sdk

import time
from datetime import datetime, timedelta
from tuya_iot import TuyaOpenAPI

# --- Configuration (Your Provided Details) ---
DEVICE_ID = "bfb2d94f8616659beajnu2"
API_REGION = "eu"  # Use 'us', 'eu', 'cn', 'in' etc. based on where your project is hosted
API_KEY = "49pmjdgqa3rr9phhsv7f"
API_SECRET = "13cc9e44af6d47e693a2aa403b0a0254"
UID = "eu1763216036773Ok1xA"
# Base URL for the European region
ENDPOINT = f"https://openapi.tuya{API_REGION}.com"

# --- Constants for Calculations ---
ELECTRICITY_COST_PER_KWH = 10.0  # Example Cost (e.g., 10 Taka/kWh)

# --- Initialize Tuya OpenAPI ---
openapi = TuyaOpenAPI(ENDPOINT, API_KEY, API_SECRET)
openapi.connect()

# --- Functions for Data Retrieval and Processing ---

def get_real_time_power():
    """
    Fetches real-time power (Wattage) and On/Off status.
    This supports the 'detailed real-time wattage' requirement.
    """
    try:
        # API path to get the device's latest status (including power and switch)
        path = f"/v1.0/devices/{DEVICE_ID}"
        response = openapi.get(path)

        if response.get('success'):
            status = response['result']['status']

            # Find the Wattage (P) and Switch Status
            current_power_watt = 0
            switch_status = "Off"

            for item in status:
                if item['code'] == 'cur_current':
                    # Tuya often returns data scaled (e.g., mA or 0.1 W), check your device docs
                    # Assuming it's in mA, converting to Amps.
                    current_amp = item['value'] / 1000.0
                    # Assuming a 220V supply and a Power Factor (PF) of 0.8 for calculation
                    # Power (W) = Voltage (V) * Current (A) * PF
                    current_power_watt = 220 * current_amp * 0.8

                if item['code'] == 'switch_1':
                    switch_status = "On" if item['value'] else "Off"

                # If your device reports power directly (code like 'cur_power' or 'power_val'):
                # if item['code'] == 'cur_power':
                #     current_power_watt = item['value'] # Scale as needed

            return {
                "success": True,
                "wattage": round(current_power_watt, 2),
                "switch_status": switch_status
            }
        else:
            return {"success": False, "message": f"API Error: {response.get('msg')}"}

    except Exception as e:
        return {"success": False, "message": f"An error occurred: {e}"}

def get_daily_energy_usage(days=1):
    """
    Fetches historical energy consumption data (kWh) for the last 'days' and calculates cost.
    This supports the 'energy usage in kWh' and 'daily operating costs' requirements.
    """
    end_time_ts = int(time.time() * 1000) # Current time in milliseconds
    start_time_ts = end_time_ts - (days * 24 * 60 * 60 * 1000)

    # API path for historical energy data
    path = f"/v1.0/devices/{DEVICE_ID}/statistics/data"

    # Example parameters for daily (24-hour) energy data
    params = {
        "code": "add_ele", # This is often the energy data point, check your device DP
        "start_time": start_time_ts,
        "end_time": end_time_ts,
        "type": "2",  # 2 means 'daily' data aggregation
    }

    response = openapi.get(path, params)

    if response.get('success') and response['result']:
        data_list = response['result']['datas']

        daily_summaries = []
        for data in data_list:
            # Tuya energy data is often in Ws (Watt-seconds) or 0.001 kWh.
            # Assuming value is in 0.001 kWh, so dividing by 1000 for kWh.
            energy_kwh = data['value'] / 1000.0
            daily_cost = energy_kwh * ELECTRICITY_COST_PER_KWH

            # Convert timestamp (often in hours or days) back to a readable date
            data_date = (datetime.now() - timedelta(days=days - data_list.index(data))).strftime('%Y-%m-%d')

            daily_summaries.append({
                "date": data_date,
                "energy_kwh": round(energy_kwh, 3),
                "daily_cost_taka": round(daily_cost, 2)
            })

        return {"success": True, "summaries": daily_summaries}
    else:
        return {"success": False, "message": f"API Error or No Data: {response.get('msg', 'No result field.')}"}

def implement_control_functionality(on_or_off):
    """
    Implements a simple On/Off control from the dashboard.
    """
    try:
        # Command to set the device status
        path = f"/v1.0/devices/{DEVICE_ID}/commands"
        commands = {
            "commands": [
                {
                    "code": "switch_1",  # Replace with your switch DP ID
                    "value": on_or_off.lower() == 'on'
                }
            ]
        }

        response = openapi.post(path, commands)

        if response.get('success'):
            return {"success": True, "message": f"Command sent: Switch turned {on_or_off}."}
        else:
            return {"success": False, "message": f"Control Error: {response.get('msg')}"}

    except Exception as e:
        return {"success": False, "message": f"An error occurred during control: {e}"}

# --- Main Script Execution (Simulates Dashboard Data) ---

if __name__ == "__main__":

    print("--- 1. Real-time Status ---")
    real_time_data = get_real_time_power()
    if real_time_data['success']:
        print(f"**Current Wattage**: {real_time_data['wattage']} W ")
        print(f"**Switch Status**: {real_time_data['switch_status']} ")
        print(f"Time: {datetime.now().strftime('%H:%M:%S')}")
    else:
        print(f"Failed to get real-time data: {real_time_data['message']}")

    print("\n--- 2. Historical Energy Usage & Cost ---")
    historical_data = get_daily_energy_usage(days=3)
    if historical_data['success']:
        print("Daily Energy Usage (kWh) and Operating Costs:")
        for summary in historical_data['summaries']:
            print(f"  {summary['date']}: Energy: {summary['energy_kwh']} kWh, Cost: {summary['daily_cost_taka']} Taka ")
    else:
        print(f"Failed to get historical data: {historical_data['message']}")

    # --- 3. Control Simulation (Uncomment to test) ---
    # print("\n--- 3. Control Functionality Test ---")
    # control_result = implement_control_functionality("Off") # Change to "On" to test turning it on
    # print(f"Control Status: {control_result['message']}")